config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'loans/progress/', to: 'loans#progress', as: :progress
  get 'loans/start_timer/', to: 'loans#start_timer', as: :start_timer
  resources :loans
  get 'loans/timer/:id', to: 'loans#timer', as: :loan_timer
  #get 'loans/', to: 'loans#index'
  #post 'loans/', to: 'loans#create'
  root 'loans#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/loan.rb
class Loan < ApplicationRecord
  validates :borrower_name, :first_payment_date, :closing_date, presence: true
  validates :loan_number, :principal_loan_amount, :interest_rate, :term, numericality: { greater_than: 0}
  validates :type_of_loan, inclusion: { in: %w(Business\ Loan Credit\ Builder\ Loan) }
  validate :closing_date_after_first_payment


  def monthly_payment
      monthly_rate = self.interest_rate / 1200.0
      a = monthly_rate * self.principal_loan_amount
      b = 1 - (1 + monthly_rate)**(-self.term)
      annuity = (a / b).round(2)
  end

  def generate_schedule
      schedule = []
      monthly_payment_amount = monthly_payment
      balance = self.principal_loan_amount
      next_payment_date = self.closing_date >> 1
      for month in 1..self.term
        next_payment_date = next_payment_date >> 1
        monthly_schedule = {}
        monthly_schedule["balance"] = balance
        monthly_schedule["next_payment_date"] = next_payment_date
        monthly_schedule["principal_payment"] = (monthly_schedule["balance"]- monthly_payment_amount).round(2)
        balance = (balance - monthly_schedule["principal_payment"]).round(2)
        monthly_schedule["end_balance"] = balance
        schedule << monthly_schedule
      end
      schedule
  end

  private

  def closing_date_after_first_payment

    return if closing_date.blank? || first_payment_date.blank?

    if closing_date < first_payment_date
      errors.add(:closing_date, "must be after the start date")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/loans_controller.rb
require 'background_job'
class LoansController < ApplicationController

  before_action :setup_loan, only:[:show, :timer]

  def index
    @loans = Loan.all
  end

  def new
    @loan = Loan.new
  end

  def show
    @schedule = @loan.generate_schedule
  end

  def create
    @loan = Loan.new(loan_params)
    if @loan.save
      redirect_to loan_timer_path(@loan)
    else
      render 'new'
    end
  end

  def timer
    background_job = BackgroundJob.new
    session[:background_job_id] = background_job.object_id
    start_timer(@loan)
  end

  def progress
    data = Hash.new
    job_object = ObjectSpace._id2ref(session[:background_job_id])
    data[:message] = "#{job_object.progress}% #{job_object.message}"
    data[:percent] = job_object.progress
    render :plain => data.to_json
  end

  private

  def start_timer(loan)
    @loan = loan
    background_job = ObjectSpace._id2ref(session[:background_job_id])
    Thread.new { background_job.run }
  end

  def setup_loan
    @loan = Loan.find(params[:id])
  end

  def loan_params
    params.require(:loan).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoanGenerator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/loans/index.html.erb
<h1 class="text-center">Listing Loans</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Loan Number</th>
      <th>Borrower Name</th>
      <th>Amount</th>
      <th>Type</th>
      <th>Details</th>
    </tr>
  </thead>
  <tbody>

    <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.loan_number %></td>
        <td><%= loan.borrower_name %></td>
        <td><%= loan.principal_loan_amount %></td>
        <td><%= loan.type_of_loan %></td>
        <td><%= link_to 'Show', loan, class: 'btn btn-xs'%></td>
      </tr>
    <% end %>

  </tbody>

</table>


<a><%= link_to 'New Loan', new_loan_url, class: 'btn btn-primary' %></a>

app/views/loans/new.html.erb
<div class="container">

  <h1 class="text-center"> Loan Deatils </h1>
  <%= form_for :loan, url: loans_url do |f| %>
    <% if @loan.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

        <ul>
        <% @loan.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label "Name" %>
      <%= f.text_field :borrower_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :loan_number %>
      <%= f.number_field :loan_number, class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= f.label :principal_loan_amount %>
      <%= f.number_field :principal_loan_amount, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :closing_date %>
      <%= f.date_field :closing_date, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :first_payment_date %>
      <%= f.date_field :first_payment_date, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :interest_rate %>
      <%= f.number_field :interest_rate, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :term %>
      <%= f.number_field :term, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :type_of_loan %>
      <%= f.radio_button :type_of_loan, 'Business Loan', :checked => true %> Business Loan
      <%= f.radio_button :type_of_loan, 'Credit Builder Loan' %> Credit Builder Loan
    </div>

    <div class="actions">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/loans/show.html.erb
<div class="text-justify">
  <h1 class="text-center">Loan Details</h1>
  <p>
    <strong>No:</strong>
    <%= @loan.loan_number %>
  </p>

  <p>
    <strong>Name: </strong>
    <%= @loan.borrower_name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= @loan.principal_loan_amount %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= @loan.type_of_loan %>
  </p>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Balance</th>
        <th>Next_payment_date</th>
        <th>Principal_payment</th>
        <th>End_balance</th>
      </tr>
    </thead>
    <tbody>

      <% @schedule.each do |month| %>
        <tr>
          <td><%= month["balance"] %></td>
          <td><%= month["next_payment_date"] %></td>
          <td><%= month["principal_payment"] %></td>
          <td><%= month["end_balance"] %></td>
        </tr>
      <% end %>

    </tbody>

  </table>

  <%= link_to 'Back', loans_url, class: 'btn btn-primary' %>
</div>

app/views/loans/timer.html.erb
<h1 class="text-center"> Please Wait </h1>
<div class="progress text-center">
  <div class="progress-bar progress-bar-striped active" role="progressbar"
   style="width:0%">
    0%
  </div>
</div>
<%= link_to 'Show loan', @loan, class: "capture hideButton" %>

<%= javascript_tag "setInterval(\"ProgressBar.start('#{progress_url}')\",1000);" %>

<%= javascript_tag "
  var href = $('.capture').attr('href');
  console.log(href);
" %>